### ISSUE TITLE
Edit countdown Timer from website directly

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/io19-countdown#6]
## Present Scenario
The countdown timeout is set as a value hardcoded in code. If countdown has to be updated to new time, it requires edit to code and a new build for the same

## Expected Change
Take an input field to set the timer and on submit, launch countdown with that time. This is to change countdown time without building with updated code again

Note: This is a forked repo, while sending PR, keep a note to send PR here and not to the main repo

**Comment by CIPHERTron** [comment]
Heyy @abhibhaw , can I work on this issue?

**Comment by abhibhaw** [comment]
Sure @CIPHERTron Assigned, Go Ahead!
